INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "center_crop", "normalize"]

DATASET:
  NAME: "ISIC2019"

  SOURCE_DOMAINS: ["BCN"]
#  SOURCE_DOMAINS: ["HAM"]

#  TARGET_DOMAINS: ["BCN"]
  TARGET_DOMAINS: ["HAM"]


  OPEN_SET: False
  KNOWN_CLASSES: ["Melanoma", "Basal cell carcinoma", "Melanocytic nevi", "Benign keratosis"]
  UNKNOWN_CLASSES: ["Unknown"]


MODEL:
  BACKBONE:

    NAME: "ViT-B/16" #"resnet50"
