INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "center_crop", "normalize"]

DATASET:
  NAME: "ISIC2019"

  SOURCE_DOMAINS: ["BCN"]
#  SOURCE_DOMAINS: ["HAM"]

#  TARGET_DOMAINS: ["BCN"]
  TARGET_DOMAINS: ["HAM"]

  # 添加OpenSet设置
  OPEN_SET: False
  # 已知类别列表
  KNOWN_CLASSES: ["Melanoma", "Basal cell carcinoma", "Melanocytic nevi", "Benign keratosis"]
  # 未知类别列表
  UNKNOWN_CLASSES: ["Unknown"]


MODEL:
  BACKBONE:
    NAME: "ViT-B/16" #"resnet50"